export {default as Menu} from './menu/menu'
export {default as SignIn} from './signin/signin'
export {default as Confirmation} from './confirtmation/confirmation'
export {default as ConfirmOrMenu} from './confirm-or-menu/confirm-or-menu'
export {default as Account} from './account/account'
export {default as MakeOs} from './make-os/make-os'
export {default as FormOs} from './form-os/form-os'
export {default as ShowOs} from './show-os/show-os'
